// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

namespace server.Migrations
{
    [DbContext(typeof(TeacherCreditContext))]
    partial class TeacherCreditContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Server.Models.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("End");

                    b.Property<string>("Name");

                    b.Property<DateTime>("Start");

                    b.HasKey("Id");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("TeachingCredits");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Server.Models.UserSemester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsBoardMember");

                    b.Property<bool>("IsCoordinator");

                    b.Property<bool>("IsResponsibleAdult");

                    b.Property<bool>("IsTeachingDrama");

                    b.Property<int>("NumberClassesTaught");

                    b.Property<int>("NumberOfLongClasses");

                    b.Property<double>("NumberRegularHoursTaught");

                    b.Property<Guid?>("SemesterId");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSemesters");
                });

            modelBuilder.Entity("Server.Models.UserSemester", b =>
                {
                    b.HasOne("Server.Models.Semester")
                        .WithMany("UserSemesters")
                        .HasForeignKey("SemesterId");

                    b.HasOne("Server.Models.User")
                        .WithMany("UserSemesters")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
